# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000


# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

cloud.aws.credentials.access-key = ${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key = ${AWS_SECRET_KEY}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
cloudfront.base-url = ${CLOUDFRONT_BASE_URL}

firebase.admin.sdk=/app/path/to/serviceAccountKey.json


