# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/skin_clear
spring.datasource.username=postgres
spring.datasource.password=ragul0506
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

cloud.aws.credentials.access-key = ${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key = ${AWS_SECRET_KEY}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
cloudfront.base-url = ${CLOUDFRONT_BASE_URL}

